### PR TITLE
Added test.yml playbook

### PR DESCRIPTION
**Pull request by psturc**
### Changes
* `test.yml` playbook for quick build + provision + test (can be run with `apb test`)
* `test-metrics-apb` role for checking accessibility of grafana & prometheus deployed routes
* `test_defaults.yml` contains variables needed for provisioning
* removed tasks for retrieving routes via shell command - the routes already exist

### How to test this
Just run `apb test` - you can watch the progress in the log of the pod running in **apb-test-metrics-apb** project
Once the pod is completed, you should get `Pod phase Succeeded without returning test results` to your output.

### CODE REVIEW

**Comment by darahayes** [comment]
@psturc This is a great start 👏  However, I have some additional feedback. This test role is **only checking that the proxy services are running**

I've found in the past few days that I've accidentally broken the APB such that the actual grafana/prometheus containers fail to start because of misconfiguration but the proxy services are up and running. In that case this test would still pass.

This is semi related to the PR https://github.com/aerogearcatalog/metrics-apb/pull/12 by @pb82 as the goal is to implement checks to ensure all of the containers provisioned by the apb are in a ready state. Perhaps when a good solution is found for that PR we would incorporate it into the tests also.

**Comment by darahayes** [comment]
@david-martin I didn't even think of that but you're right 😄

**Comment by darahayes** [comment]
I guess that potentially raises the question about where should those checks ideally live? What makes the most sense? I'd argue that the test is the most appropriate place to put them but that is just my opinion. Feedback welcome!

**Comment by david-martin** [comment]
@darahayes for the RHMAP 4.x Ansible Installer, we didn't have any checks (initially) that things provisioned correctly. There were only readiness & liveness checks on the services, but no overarching view of if everything was running.
We learned from that and added checks after each provisioning step to ensure what we said to provision was actually provisioned OK and was running. This led to a more robust installer, and faster feedback to the person running the installer.
I think there is great value in having checks for things actually running OK in the provision tasks.

Where I see testing adding value here is verifying that the thing can actually be used (more than just running). 
To try think of an example, if someone removed/modified a Route and broke it (no longer pointing to the right service), this is a functionality bug that an apb test should pick up on.
The Route would still be created OK in kubernetes, which is technically a successful provision.

**Comment by darahayes** [comment]
@david-martin Those are really good points. I would lack the context and previous experiences here. Sounds good to me! In that case, I think this PR is good to merge 👍

**Comment by pb82** [comment]
@psturc The test fails for me locally with:

```
⇒  apb test
Finished writing dockerfile.
Building APB using tag: [metrics-apb]
Successfully built APB image: metrics-apb
Creating project apb-test-metrics-apb
Created project
Creating service account in apb-test-metrics-apb
Created service account
Creating role binding for apb-test-metrics-apb7wkpm in apb-test-metrics-apb
Created Role Binding
Creating pod with image metrics-apb in apb-test-metrics-apb
Created Pod
Unable to retrieve test result.
Deleting project apb-test-metrics-apb
Project deleted
```

The logs of the container are:

```
TASK [test-metrics-apb : Check that the prometheus webpage is accessible] ******
FAILED - RETRYING: Check that the prometheus webpage is accessible (10 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (9 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (8 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (7 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (6 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (5 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (4 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (3 retries left).
FAILED - RETRYING: Check that the prometheus webpage is accessible (2 retries left).
```

It actually ends with 2 retries left.

**Comment by darahayes** [comment]
@pb82 could be a timing issue. Perhaps after your PR is merged, this test will pass.

**Comment by pb82** [comment]
@darahayes it's possible, the containers take a while to become ready. @psturc i've merged my PR now, can you please rebase? I'll try again then.

**Comment by psturc** [comment]
@darahayes good point. I've tried this on 2 of my OpenShift instances and the test has passed.
Has anybody else tried this locally?

**Comment by wtrocki** [comment]
@psturc To cover all 4 running pods we will need to add additional 2 calls that will hit grafana and prometeus service. Currently we hitting openshift auth proxy servers.

**Comment by david-martin** [comment]
What can we say is actually running if we get a successful response from
the auth proxy? Is it not the case that the pod will only be added to the
service load balancer if all containers are ready (both oauth proxy and
prometheus) ? @Maleck13 any thoughts here?

**Comment by pb82** [comment]
@psturc i've tried it two more times with the updated PR but i always hit the `Unable to retrieve test result`

**Comment by psturc** [comment]
@pb82 That's expected behaviour, because it is a known issue: https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/issues/190

Important is this message: `Pod phase Succeeded without returning test results`

**Comment by pb82** [comment]
@psturc Ok, it's working for me too. I had some issues resolving the .nip.io URLs but once they work the script outputs `Pod phase Succeeded without returning test results`

**Comment by maleck13** [comment]
@david-martin haven't read the whole thread, but the pod would be added to the service once the liveness and readiness probes have passed

**Comment by david-martin** [comment]
Thanks @maleck13. So based on that, the prometheus test that asserts some text in a response from the oauth proxy tells use that both the oauth proxy container and the prometheus container (both in the same Pod) are both running OK.
@darahayes @wtrocki Does that sound OK to you? i.e. no need for additional checks to cover all 4 containers.

**Pull request merged**
