### PR TITLE
Mobile app metrics detail dashboard

### PR DESCRIPTION
**Pull request by aliok**
Screenshot:

screenshot from 2018-03-06 15-52-29

### CODE REVIEW

**Comment by aliok** [comment]
cc @pb82 @david-martin 
Pushed new commits to conform John's requirements. Screenshot attached.

**Comment by pb82** [comment]
@aliok I can't find that dashboard, i still see the old one. There is the following link:

bildschirmfoto 2018-03-07 um 10 53 40

But when i click it i get `Dashboard not found`. I built and pushed the apb from this branch locally.

**Comment by aliok** [comment]
@pb82 pushed the fixes for the things we've tried together. merging this now...

**Comment by pb82** [comment]
@aliok Ok, i'm testing those changes now

**Comment by pb82** [comment]
@aliok I can confirm that it's working now (sans the Grafana bug).

**Pull request merged**
