### PR TITLE
Make mobile-services dashboard the home dashboard

### PR DESCRIPTION
**Pull request by aliok**
JIRA: https://issues.jboss.org/browse/AEROGEAR-2718

How to verify:
* Check out this branch
* `apb build && apb push`
* Provision metrics apb
* Open Grafana route
* Verify that mobile services dashboard is shown by default

### CODE REVIEW

**Comment by psturc** [comment]
@aliok apb test is failing. I'll give it a try locally.

**Comment by aliok** [comment]
@psturc I don't get why it is failing. maybe need to add more trials in the failing thing here:
https://jenkins-wendy.ci.feedhenry.org/blue/organizations/jenkins/AeroGearCatalog%2Fmetrics-apb/detail/PR-58/4/pipeline

**Comment by aliok** [comment]
thanks @psturc merged this one w/o waiting you

**Comment by psturc** [comment]
@aliok no worries, I'll create a separate PR for that.

**Pull request merged**
