### PR TITLE
AEROGEAR-2016 label serviceinstance

### PR DESCRIPTION
**Pull request by pb82**
We need to add a label with the service name to the service instance for the mobile cli.

ping @dimitraz @maleck13

### CODE REVIEW

**Comment by pb82** [comment]
retest this please

**Comment by darahayes** [comment]
If it's critical that we have labels on every service instance, I feel this should be fixed in the upstream APB tool as opposed to introducing this logic in every APB. This implementation seems like a workaround.

It would be better if we could simply declare a service label in the `apb.yml` spec and have that label attached to the service instance by the APB tool. This block of code in `ansible-playbook-bundle` pulls out the metadata from `apb.yml` and creates a yaml definition for the service instance. https://github.com/ansibleplaybookbundle/ansible-playbook-bundle/blob/master/src/apb/engine.py#L1180-L1217

It should be a simple enough fix to also parse a label and add it to the service instance definition.

It might be worth reaching out to the Ansible playbook team to get this fixed properly. They'd be happy to help out I think.

@pb82 @david-martin what do you guys think?

**Comment by pb82** [comment]
@darahayes at the moment the metadata field of apb.yml only accepts a limited set of key value pairs. To support labels it would have to accept a map value. I agree that this would be preferable and it seems like a reasonable contribution or feature request.

@maleck13 what do you think?

**Comment by maleck13** [comment]
> If it's critical that we have labels on every service instance, I feel this should be fixed in the upstream APB tool as opposed to introducing this logic in every APB. This implementation seems like a workaround.

I don't think the APB tool is where this would be needed. The ServiceInstance Object is controlled by the service catalog not the APB or the ASB.

The apb.yaml defines the ClusterServiceClass and a ClusterServiceInstance is a instance of that class. 
The broker responds to the service catalog, with a set of services
https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-objects
We already define metadata which is made available via the ClusterServiceClass as per the spec.

I think if we wanted a feature where arbitary labels could be specified from a broker it would need to be discussed with the ServiceCatalog team.

Another thing to consider here is brokers aren't tied to OpenShift. Many brokers may not br provisioning services in K8s or running in k8s / OSCP they may be running on a VM somewhere and have not interest in interacting with the serviceinstance object

**Comment by pb82** [comment]
@maleck13 @darahayes as an alternative, we could create a dedicated role for that and bundle it together with https://github.com/aerogear/oc-patch-file-to-configmap-role in a 'aerogear-asb-tools' repo.

**Comment by darahayes** [comment]
@maleck13 @pb82 I don't think the apb makes any changes to the service instance after creation. I think my PR may be misguided. 

However, what if we could figure out how to get the service instance name/identifier passed as variable into APB from its caller? Basically a halfway measure that makes APBs *service instance aware*. We'd still have to add the labels ourselves but we wouldn't need to do the weird querying logic to find the service instance in the first place. Just an idea

**Comment by maleck13** [comment]
@darahayes that is what is happening the variable ```_apb_service_instance_id``` is passed in to the apb from the service broker

**Comment by pb82** [comment]
@darahayes the querying is required because only the UID gets passed into Ansible. But oc/kubectl commands need a resource name.

**Pull request merged**
