### PR TITLE
WIP security metrics dashboard

### PR DESCRIPTION
**Pull request by paolobueno**
Related to https://issues.jboss.org/browse/AEROGEAR-2244

### CODE REVIEW

**Comment by paolobueno** [comment]
Currrent draft available at https://snapshot.raintank.io/dashboard/snapshot/prY1QUv4oiUFGdTEKoLpuvKHIvs1b3vz

**Comment by paolobueno** [comment]
ping @aliok @darahayes @david-martin. Going to share the snapshot in the mailing list, can't add reviewers myself

**Comment by aliok** [comment]
@paolobueno I am trying to see it locally but having problems with the data seed application (compile errors). Is it possible that some code is not checked in?

**Comment by darahayes** [comment]
I'll be quite honest... I have almost no idea what most of this dashboard means. I'm not a product person so I don't know what is and what isn't valuable here. That said, I would have no interest in how many self defence checks have passed. I expect things to pass. I want to know about things that are alarming. 

Some things that would make sense to me personally:



* To

**Comment by darahayes** [comment]
Sorry folks, I closed this by accident :/

**Comment by darahayes** [comment]
I'll be quite honest... I have almost no idea what most of this dashboard means. I'm not a product person so I don't know what is and what isn't valuable here. 

That said, I would have no interest in things like total pass rate. I expect things to pass. **I want to know about things that are failing.** Things that I might need to take actions on.

Some visualisations/insights that would make sense to me personally:

* total failure rate (total failures / total) for each type of check. i.e. something that displays: Debugger: 25%, Screenlock 21%, Rooted: 12%, ..., Perhaps a row of those single value boxes (one for each type)?
* failure rate (same as above) but for a given period, e.g. last 30 days.
* Perhaps a line chart that shows the failure rate over time for each type (not sure about this one. Might be too much info in one visualisation)

^^ Repeat this for each individual platform

**Comment by aliok** [comment]
I guess you didn't add this new file to the configmap because it is a WIP.

**Comment by aliok** [comment]
@paolobueno how to generate data on App metrics database on OpenShift using the script?
I tried to create a route for the Postgres instance but I wasn't successful that way.

I actually am against generating data using this approach. We should better send HTTP requests to the service instead of creating stuff in the database using the service directly. 
* It is hard to feed
* To me it seems a bit unnecessary to have this script in the codebase
* There was already something I created: https://github.com/aliok/aerogear-mobile-metrics-api-data-generator I know it needed some changes but we could've just modify this instead of creating something from scratch.

cc @darahayes

**Comment by paolobueno** [comment]
@aliok thanks for already taking a look at this, was waiting to sync up with you for some help with getting it on openshift since I was also only testing locally. Going to start testing it out on openshift today.

Wanted to develop the dashboard straight in the openshift instance so I too tried creating a route to reach the postgres instance inside openshift directly but also failed.

I was planning to do it via http: https://github.com/aerogear/aerogear-app-metrics/blob/master/scripts/data-fill.go#L96 just by refactoring `Create()` to a strategy interface and adding another flag to the cli.

Another change I'd like to make to the server itself to facilitate testing is to allow for a custom metrics time to be set. I've noticed we're using the server's `event_time` in the queries and ignoring `client_time` (considering both in the sql correctly could be pretty hard, so I agree with this approach), but since this is set by the server time we can't simulate a long-running scenario for metrics yet.
@darahayes  ^^

I didn't use your util because I wasn't aware of it, but having the generator directly using the same data models as the rest of the server might have some benefits down the line. Even if yours is in node, I'd like to have it in the server's repo for findability.

**Comment by darahayes** [comment]
+1 on using http. Let's not over engineer. The data-fill.go script can be changed to just make a simple http call instead of Create(). Much more portable.

No flags no options the usage should be ridiculously simple.  

```
go run data-fill.go <hostname>
```

**Comment by aliok** [comment]
Guys,

I created https://github.com/aerogearcatalog/metrics-apb/pull/44 and closing this one as I have created a mess and pushing more commits on top of this branch makes things ugly.

**Pull request closed without merging**
